services:
  api:
    build:
      context: ./images/python
    image: sistema_de_autenticacao_auth_api
    container_name: sistema_de_autenticacao_container_auth_api
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./src:/app
    expose:
      - 8000
  
  nginx:
    build:
      context: ./images/nginx
    image: nginx_sistema_de_autenticacao_auth_api
    container_name: nginx_sistema_de_autenticacao_container_auth_api
    volumes:
      - ./src:/app
    ports:
      - 80:80
    depends_on:
      - api

  sqlserver:
    build:
      context: ./images/sql_server
    image: sistema_de_autenticacao_auth_sqlserver
    container_name: sistema_de_autenticacao_container_auth_sqlserver
    volumes:
      - ./src:/app
    ports:
      - 1433:1433
    depends_on:
      - api