services:
  api:
    build:
      context: ./images/python
    image: sistema_de_autenticacao_dev_auth_api
    container_name: sistema_de_autenticacao_dev_container_auth_api
    command: python /app/manage.py runserver 0:8000
    volumes:
      - ./src:/app
    ports:
      - "8000:8000"

  sqlserver: 
    image: "mcr.microsoft.com/mssql/server:2017-latest"
    environment:
      - SA_PASSWORD=Pass@word
      - ACCEPT_EULA=Y
    ports:
      - "5434:1433"

  
  redis:
    image: redis:6.2-alpine
    ports:
      - "6379:6379"

  redis-commander:
    container_name: redis_commander_sistema_autenticacao_dev_container_auth_redis_commander
    image: rediscommander/redis-commander:latest
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8082:8081"

volumes:
  dbdata: