services:
  api:
    build:
      context: ./images/python
    image: sistema_de_autenticacao_dev_auth_api
    container_name: sistema_de_autenticacao_dev_container_auth_api
    command: python /app/manage.py runserver 0:8000
    volumes:
      - ./src:/app
    ports:
      - "8000:8000"
  sqlserver: 
    image: "mcr.microsoft.com/mssql/server"
    environment:
      SA_PASSWORD: "Master@123"
      ACCEPT_EULA: "Y"

volumes:
  dbdata: